"""Tests for the partial-GLB VRM metadata extractor.

Tests the parsing core (parse_glb, parse_glb_header, extract_vrm_from_gltf)
against synthetic fixture files — no network calls. The HTTP range-request
path (fetch_vrm_meta / get_range) is tested via mock to verify the
range-unsupported fallback behavior.

Fixtures are generated by tests/fixtures/generate_vrm_fixtures.py.
"""

from __future__ import annotations

import json
import struct
import sys
from pathlib import Path
from unittest.mock import patch

import pytest

_REPO_ROOT = Path(__file__).resolve().parent.parent
if str(_REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(_REPO_ROOT))

from scripts.extract_vrm_meta import (  # noqa: E402
    GLB_MAGIC,
    GLB_VERSION_2,
    JSON_CHUNK_TYPE,
    extract_vrm_from_gltf,
    fetch_vrm_meta,
    parse_glb,
    parse_glb_header,
    summarize_meta,
)

FIXTURE_DIR = _REPO_ROOT / "tests" / "fixtures" / "vrm"


def _fixture(name: str) -> bytes:
    return (FIXTURE_DIR / name).read_bytes()


# ─── parse_glb_header ──────────────────────────────────────────────────────


def test_header_too_short():
    with pytest.raises(ValueError, match="Header too short"):
        parse_glb_header(b"\x00" * 10)


def test_header_parses_valid_glb():
    data = _fixture("vrm_0x_minimal.glb")
    magic, version, total, jlen, ctype = parse_glb_header(data[:20])
    assert magic == GLB_MAGIC
    assert version == GLB_VERSION_2
    assert ctype == JSON_CHUNK_TYPE
    assert total == len(data)
    assert jlen > 0


# ─── parse_glb: VRM 0.x ────────────────────────────────────────────────────


def test_parse_vrm_0x_minimal():
    data = _fixture("vrm_0x_minimal.glb")
    result = parse_glb(data, "test://0x")
    assert result["vrm_spec"] == "0.x"
    meta = result["raw_meta"]
    assert meta is not None
    assert meta["title"] == "Test VRM 0.x"
    assert meta["author"] == "TestAuthor"
    assert meta["allowedUserName"] == "Everyone"
    # Intentional misspelling preserved
    assert meta["commercialUssageName"] == "Allow"
    assert meta["licenseName"] == "CC0"
    assert result["total_length"] == len(data)


def test_parse_vrm_0x_preserves_misspelled_fields():
    """VRM 0.x field names have intentional misspellings — read as written."""
    data = _fixture("vrm_0x_minimal.glb")
    result = parse_glb(data)
    meta = result["raw_meta"]
    assert "violentUssageName" in meta
    assert "sexualUssageName" in meta
    assert "commercialUssageName" in meta
    # Correctly-spelled variants must NOT be present
    assert "violentUsageName" not in meta
    assert "sexualUsageName" not in meta


# ─── parse_glb: VRM 1.0 ────────────────────────────────────────────────────


def test_parse_vrm_1_0_minimal():
    data = _fixture("vrm_1_0_minimal.glb")
    result = parse_glb(data, "test://1.0")
    assert result["vrm_spec"] == "1.0"
    meta = result["raw_meta"]
    assert meta is not None
    assert meta["name"] == "Test VRM 1.0"
    assert meta["authors"] == ["TestAuthor"]
    assert meta["avatarPermission"] == "everyone"
    assert meta["commercialUsage"] == "personalProfit"
    assert meta["allowRedistribution"] is True
    assert meta["modification"] == "allowModificationRedistribution"


def test_vrm_1_0_required_fields_present():
    """VRM 1.0 meta requires name, authors[], and licenseUrl."""
    data = _fixture("vrm_1_0_minimal.glb")
    result = parse_glb(data)
    meta = result["raw_meta"]
    assert "name" in meta
    assert "authors" in meta
    assert "licenseUrl" in meta


# ─── parse_glb: error cases ────────────────────────────────────────────────


def test_parse_malformed_not_glb():
    data = _fixture("malformed_not_glb.glb")
    with pytest.raises(ValueError, match="Not a GLB file"):
        parse_glb(data)


def test_parse_no_vrm_extension():
    data = _fixture("no_vrm_extension.glb")
    with pytest.raises(ValueError, match="no VRM extension"):
        parse_glb(data)


def test_parse_wrong_glb_version():
    """Construct a GLB with version 1 instead of 2."""
    json_bytes = json.dumps({"asset": {"version": "2.0"}}).encode()
    while len(json_bytes) % 4:
        json_bytes += b"\x00"
    total = 12 + 8 + len(json_bytes)
    header = struct.pack("<IIIIII", GLB_MAGIC, 1, total, len(json_bytes), JSON_CHUNK_TYPE, 0)
    # Actually GLB header is only 12 bytes, then chunk header is 8 bytes
    header = struct.pack("<III", GLB_MAGIC, 1, total)
    chunk = struct.pack("<II", len(json_bytes), JSON_CHUNK_TYPE) + json_bytes
    with pytest.raises(ValueError, match="Unsupported GLB version"):
        parse_glb(header + chunk)


def test_parse_first_chunk_not_json():
    """Construct a GLB where the first chunk type is BIN, not JSON."""
    json_bytes = b"\x00" * 4
    total = 12 + 8 + len(json_bytes)
    header = struct.pack("<III", GLB_MAGIC, GLB_VERSION_2, total)
    chunk = struct.pack("<II", len(json_bytes), 0x004E4942) + json_bytes  # BIN type
    with pytest.raises(ValueError, match="First chunk is not JSON"):
        parse_glb(header + chunk)


# ─── extract_vrm_from_gltf ─────────────────────────────────────────────────


def test_extract_vrm_1_0_from_gltf():
    gltf = {"extensions": {"VRMC_vrm": {"meta": {"name": "X"}}}}
    result = extract_vrm_from_gltf(gltf, "url", 100)
    assert result["vrm_spec"] == "1.0"
    assert result["raw_meta"] == {"name": "X"}


def test_extract_vrm_0x_from_gltf():
    gltf = {"extensions": {"VRM": {"meta": {"title": "Y"}}}}
    result = extract_vrm_from_gltf(gltf, "url", 200)
    assert result["vrm_spec"] == "0.x"
    assert result["raw_meta"] == {"title": "Y"}


def test_extract_prefers_vrm_1_0_when_both_present():
    """If both VRM and VRMC_vrm are present, prefer 1.0."""
    gltf = {"extensions": {
        "VRM": {"meta": {"title": "0x"}},
        "VRMC_vrm": {"meta": {"name": "1.0"}},
    }}
    result = extract_vrm_from_gltf(gltf, "url", 300)
    assert result["vrm_spec"] == "1.0"


def test_extract_no_extensions():
    with pytest.raises(ValueError, match="no VRM extension"):
        extract_vrm_from_gltf({}, "url", 100)


def test_extract_extensions_but_no_vrm():
    gltf = {"extensions": {"KHR_draco": {}}}
    with pytest.raises(ValueError, match="no VRM extension"):
        extract_vrm_from_gltf(gltf, "url", 100)


# ─── fetch_vrm_meta: HTTP mocking (range-unsupported fallback) ─────────────


def test_fetch_vrm_meta_range_supported():
    """Simulate a server that returns 206 Partial Content."""
    data = _fixture("vrm_0x_minimal.glb")
    header_bytes = data[:20]
    json_bytes = data[20 : 20 + struct.unpack("<I", data[12:16])[0]]

    def mock_get_range(url, start, end, timeout=30.0):
        if start == 0:
            return header_bytes
        return data[start : end + 1]

    with patch("scripts.extract_vrm_meta.get_range", side_effect=mock_get_range):
        result = fetch_vrm_meta("https://example.com/test.glb")
    assert result["vrm_spec"] == "0.x"
    assert result["raw_meta"]["title"] == "Test VRM 0.x"


def test_fetch_vrm_meta_range_unsupported_returns_full():
    """Simulate a server that ignores Range and returns 200 with full content.

    get_range handles this by slicing the full response to the requested bytes.
    """
    data = _fixture("vrm_1_0_minimal.glb")

    def mock_get_range(url, start, end, timeout=30.0):
        # Server ignores Range, returns full content (200 status)
        requested_len = end - start + 1
        return data[:requested_len] if start == 0 else data[start : start + requested_len]

    with patch("scripts.extract_vrm_meta.get_range", side_effect=mock_get_range):
        result = fetch_vrm_meta("https://example.com/test.glb")
    assert result["vrm_spec"] == "1.0"
    assert result["raw_meta"]["name"] == "Test VRM 1.0"


def test_fetch_vrm_meta_malformed_raises():
    """fetch_vrm_meta raises on malformed GLB."""
    data = _fixture("malformed_not_glb.glb")

    def mock_get_range(url, start, end, timeout=30.0):
        return data[start : end + 1]

    with patch("scripts.extract_vrm_meta.get_range", side_effect=mock_get_range):
        with pytest.raises(ValueError, match="Not a GLB file"):
            fetch_vrm_meta("https://example.com/bad.glb")


# ─── summarize_meta: spec-aware field mapping ──────────────────────────────


def test_summarize_meta_0x_reads_misspelled_fields():
    data = _fixture("vrm_0x_minimal.glb")
    result = parse_glb(data)
    summary = summarize_meta(result["raw_meta"], "0.x")
    assert summary["title"] == "Test VRM 0.x"
    assert summary["author"] == "TestAuthor"
    assert summary["license"] == "CC0"
    assert summary["allowed_user"] == "Everyone"
    assert summary["commercial"] == "Allow"


def test_summarize_meta_1_0_reads_correct_fields():
    """VRM 1.0 uses name/authors[]/licenseUrl — the 0.x field names are absent."""
    data = _fixture("vrm_1_0_minimal.glb")
    result = parse_glb(data)
    summary = summarize_meta(result["raw_meta"], "1.0")
    assert summary["title"] == "Test VRM 1.0"
    # authors[] is joined into a single author string
    assert summary["author"] == "TestAuthor"
    # license comes from licenseUrl, never licenseName, on 1.0
    assert summary["license"] == result["raw_meta"]["licenseUrl"]
    assert summary["allowed_user"] == "everyone"
    assert summary["commercial"] == "personalProfit"
    assert summary["redistribution"] is True


def test_summarize_meta_1_0_does_not_fall_back_to_0x_names():
    """A 1.0 meta lacking 0.x names must still yield author + license."""
    meta = {"name": "N", "authors": ["A", "B"], "licenseUrl": "https://vrm.dev/licenses/1.0/"}
    summary = summarize_meta(meta, "1.0")
    assert summary["author"] == "A, B"
    assert summary["license"] == "https://vrm.dev/licenses/1.0/"


# ─── real fixture cross-check ──────────────────────────────────────────────


def test_real_fixture_token_500_parses():
    """The 1.4MB real VRM fixture should parse successfully via parse_glb."""
    data = _fixture("token_500_vrm.glb")
    result = parse_glb(data, "test://real")
    assert result["vrm_spec"] in ("0.x", "1.0")
    assert result["raw_meta"] is not None
    assert result["total_length"] == len(data)
